version: "3.7"

services:
  backend:
    image: node:14-alpine
    working_dir: "/backend"
    container_name: bvplayer_backend
    command: sh -c "yarn && yarn start"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./backend/tracks:/tracks
      - ./backend/posters:/posters
      - backend_data:/backend/node_modules
    networks:
      - bvplayer_network

  frontend:
    image: node:14-alpine
    working_dir: "/frontend"
    container_name: bvplayer_frontend
    command: sh -c "yarn && yarn start"
    depends_on:
      - backend
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ./frontend:/frontend
      - frontend_data:/frontend/node_modules
    networks:
      - bvplayer_network
    environment:
      CHOKIDAR_USEPOLLING: "true"
      API_URL: "localhost:8000"

  postgres:
    image: "postgres:13.2-alpine"
    env_file: ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bvplayer_network

volumes:
  backend_data:
    driver: local
  frontend_data:
    driver: local
  postgres-data:
    driver: local

networks:
  bvplayer_network:
    driver: bridge
